#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""EXPL-DATA-PIPELINE: validate, sync, doctor for explanation JSON files."""

import argparse
import json
import os
import re
import sys
from pathlib import Path

# Windows cp932 safety: keep stdout/stderr UTF-8 even if console is OEM.
if sys.platform == "win32" and os.environ.get("PYTHONIOENCODING") is None:
    # Force UTF-8 for stdout/stderr; this only affects python-level encoding.
    sys.stdout = open(sys.stdout.fileno(), "w", encoding="utf-8", errors="replace", closefd=False)
    sys.stderr = open(sys.stderr.fileno(), "w", encoding="utf-8", errors="replace", closefd=False)


# Project layout: script lives in tools/, project root is its parent.
TOOLS_DIR = Path(__file__).resolve().parent
ROOT_DIR = TOOLS_DIR.parent
DATA_DIR = ROOT_DIR / "data"
EXPL_DIR = DATA_DIR / "explanations"
BUNDLE_PATH = ROOT_DIR / "js" / "data_bundle.js"

BUNDLE_HEADER = "// GENERATED by tools/expl_pipeline.py — do not edit"

# Fixed order mapping from JSON filename to window.FT.DATA_* key.
DATA_MAP = [
    ("skill_graph.json", "DATA_GRAPH"),
    ("checks.json", "DATA_CHECKS"),
    ("copy_ja.json", "DATA_COPY"),
    ("math_cards.json", "DATA_MATH"),
    ("hotspots.json", "DATA_HOTSPOTS"),
    ("proof_scripts.json", "DATA_PROOF"),
    ("symbol_readings.json", "DATA_READINGS"),
]


def _msg(text, level=None):
    prefix = ""
    if level == "ok":
        prefix = "[ok] "
    elif level == "warn":
        prefix = "[warn] "
    elif level == "fail":
        prefix = "[FAIL] "
    print(prefix + text)


def load_json(path):
    with open(path, "r", encoding="utf-8") as f:
        return json.load(f)


def dump_json(obj):
    return json.dumps(obj, ensure_ascii=False, separators=(",", ":"), sort_keys=False)


def dump_pretty_json(obj, path):
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        json.dump(obj, f, ensure_ascii=False, indent=2)
        f.write("\n")


def load_proof_merged():
    """Merge explanations/_meta.json + P-*.json into the legacy proof shape.

    Returns dict with keys: schema_version, ref_nodes, note, scripts, node_index.
    Falls back to data/proof_scripts.json if explanations dir is missing/empty.
    """
    if not EXPL_DIR.is_dir():
        _msg(f"{EXPL_DIR} missing; falling back to data/proof_scripts.json", "warn")
        return load_json(DATA_DIR / "proof_scripts.json")

    meta_path = EXPL_DIR / "_meta.json"
    if not meta_path.exists():
        _msg(f"{meta_path} missing; falling back to data/proof_scripts.json", "warn")
        return load_json(DATA_DIR / "proof_scripts.json")

    meta = load_json(meta_path)
    scripts = {}
    script_order = meta.get("script_order")

    if isinstance(script_order, list) and script_order:
        ordered_ids = script_order
    else:
        ordered_ids = sorted(p.stem for p in EXPL_DIR.glob("P-*.json"))
        _msg("script_order missing/empty in _meta.json; using sorted P-*.json", "warn")

    for sid in ordered_ids:
        path = EXPL_DIR / f"{sid}.json"
        if not path.exists():
            raise FileNotFoundError(f"expected explanation file missing: {path}")
        script = load_json(path)
        if not isinstance(script, dict):
            raise ValueError(f"{path} does not contain a JSON object")
        if script.get("id") != sid:
            raise ValueError(f"{path} id mismatch: expected {sid}, got {script.get('id')}")
        if path.stem != sid:
            raise ValueError(f"{path} filename stem mismatch: expected {sid}")
        scripts[sid] = script

    return {
        "schema_version": meta.get("schema_version"),
        "ref_nodes": meta.get("ref_nodes"),
        "note": meta.get("note"),
        "scripts": scripts,
        "node_index": meta.get("node_index"),
    }


def merge(_args):
    """Regenerate data/proof_scripts.json from explanations/*."""
    print("merge: explanations/ -> data/proof_scripts.json")
    proof = load_proof_merged()
    dump_pretty_json(proof, DATA_DIR / "proof_scripts.json")
    _msg("generated data/proof_scripts.json", "ok")
    return 0


# ---------------------------------------------------------------------------
# validate
# ---------------------------------------------------------------------------

def validate_proof_scripts(proof_data):
    """Return (errors, warnings) lists."""
    errors = []
    warnings = []

    scripts = proof_data.get("scripts")
    node_index = proof_data.get("node_index")

    if not isinstance(scripts, dict):
        errors.append("scripts must be a dict")
        return errors, warnings
    if not isinstance(node_index, dict):
        errors.append("node_index must be a dict")
        return errors, warnings

    # node_index reverse consistency
    for node, script_id in node_index.items():
        if script_id not in scripts:
            errors.append(f"node_index[{node}] -> {script_id} not found in scripts")

    # Check every node_index value exists in scripts already covered.
    # Also check each script.
    for key, script in scripts.items():
        if not isinstance(script, dict):
            errors.append(f"script[{key}] is not a dict")
            continue

        # id equals key
        if script.get("id") != key:
            errors.append(f"script[{key}].id != '{key}'")

        # required non-empty strings
        for field in ("id", "node", "title", "intuition_1line", "why_needed"):
            val = script.get(field)
            if not isinstance(val, str) or not val.strip():
                errors.append(f"script[{key}].{field} missing or empty")

        # node_index reverse
        node = script.get("node")
        if node and node_index.get(node) != key:
            errors.append(f"script[{key}].node reverse mismatch: node_index[{node}] != {key}")

        # story_steps
        story_steps = script.get("story_steps")
        if not isinstance(story_steps, list) or not (3 <= len(story_steps) <= 6):
            errors.append(f"script[{key}].story_steps length not in 3-6")
        else:
            for i, step in enumerate(story_steps):
                if not isinstance(step, dict):
                    errors.append(f"script[{key}].story_steps[{i}] not a dict")
                    continue
                for field in ("title", "body"):
                    val = step.get(field)
                    if not isinstance(val, str) or not val.strip():
                        errors.append(f"script[{key}].story_steps[{i}].{field} empty")

        # morph_steps
        morph_steps = script.get("morph_steps")
        if not isinstance(morph_steps, list) or not (2 <= len(morph_steps) <= 8):
            errors.append(f"script[{key}].morph_steps length not in 2-8")

        # puzzle_cards + puzzle_order
        puzzle_cards = script.get("puzzle_cards")
        puzzle_order = script.get("puzzle_order")
        if isinstance(puzzle_cards, list) and isinstance(puzzle_order, list):
            card_ids = set()
            for c in puzzle_cards:
                if isinstance(c, dict):
                    cid = c.get("id")
                    if isinstance(cid, str):
                        card_ids.add(cid)
            for i, pid in enumerate(puzzle_order):
                if pid not in card_ids:
                    errors.append(f"script[{key}].puzzle_order[{i}]={pid} not in puzzle_cards")
        else:
            errors.append(f"script[{key}] missing puzzle_cards/puzzle_order")

        # geometry: warn only if demo missing/empty
        geometry = script.get("geometry")
        if geometry is not None:
            if not isinstance(geometry, dict):
                warnings.append(f"script[{key}].geometry is not a dict")
            else:
                demo = geometry.get("demo")
                if not isinstance(demo, str) or not demo.strip():
                    warnings.append(f"script[{key}].geometry.demo missing or empty")

    return errors, warnings


def validate(_args):
    all_ok = True
    print("validate: explanation data")

    # Validate all data files are valid JSON.
    for filename, key in DATA_MAP:
        path = DATA_DIR / filename
        if not path.exists():
            _msg(f"missing {path}", "fail")
            all_ok = False
            continue
        try:
            load_json(path)
            _msg(f"{filename} -> {key} valid JSON", "ok")
        except json.JSONDecodeError as e:
            _msg(f"{filename} JSON parse error: {e}", "fail")
            all_ok = False

    # Proof-specific validation: merge explanations in memory and validate.
    try:
        proof_data = load_proof_merged()
    except (FileNotFoundError, json.JSONDecodeError, ValueError) as e:
        _msg(f"merge-in-memory failed: {e}", "fail")
        return 1

    errors, warnings = validate_proof_scripts(proof_data)
    for w in warnings:
        _msg(f"proof_scripts: {w}", "warn")
    if errors:
        all_ok = False
        for e in errors:
            _msg(f"proof_scripts: {e}", "fail")
    else:
        _msg("proof_scripts: semantic validation passed", "ok")

    # Validate each P-*.json file exists for script_order.
    if EXPL_DIR.is_dir() and (EXPL_DIR / "_meta.json").exists():
        try:
            meta = load_json(EXPL_DIR / "_meta.json")
            script_order = meta.get("script_order", [])
            for sid in script_order:
                path = EXPL_DIR / f"{sid}.json"
                if not path.exists():
                    _msg(f"script_order references missing {path}", "fail")
                    all_ok = False
            if script_order:
                _msg("explanations: script_order files present", "ok")
        except json.JSONDecodeError as e:
            _msg(f"_meta.json parse error: {e}", "fail")
            all_ok = False

    return 0 if all_ok else 1


# ---------------------------------------------------------------------------
# sync
# ---------------------------------------------------------------------------

def sync(_args):
    print("sync: merge -> data/*.json -> js/data_bundle.js")

    # Always regenerate proof_scripts.json from explanations before bundling.
    code = merge(_args)
    if code != 0:
        return code

    pieces = []
    for filename, key in DATA_MAP:
        path = DATA_DIR / filename
        if not path.exists():
            _msg(f"missing source {path}", "fail")
            return 1
        data = load_json(path)
        line = f"window.FT.{key} = {dump_json(data)};"
        pieces.append(line)

    lines = [BUNDLE_HEADER, "window.FT = window.FT || {};"] + pieces

    BUNDLE_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(BUNDLE_PATH, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")

    _msg(f"generated {BUNDLE_PATH}", "ok")
    return 0


# ---------------------------------------------------------------------------
# doctor
# ---------------------------------------------------------------------------

def doctor(_args):
    print("doctor: checking generated bundle and proof merge")
    all_ok = True

    # b) proof_scripts.json == merged explanations
    proof_path = DATA_DIR / "proof_scripts.json"
    if proof_path.exists():
        try:
            proof_disk = load_json(proof_path)
            proof_merged = load_proof_merged()
            if proof_disk == proof_merged:
                _msg("proof_scripts.json == merged explanations", "ok")
            else:
                _msg("proof_scripts.json differs from merged explanations", "fail")
                all_ok = False
        except (FileNotFoundError, json.JSONDecodeError, ValueError) as e:
            _msg(f"merge comparison failed: {e}", "fail")
            all_ok = False
    else:
        _msg("proof_scripts.json missing", "fail")
        all_ok = False

    if not BUNDLE_PATH.exists():
        _msg(f"bundle missing: {BUNDLE_PATH}", "fail")
        return 1

    with open(BUNDLE_PATH, "r", encoding="utf-8") as f:
        content = f.read()

    lines = content.splitlines()
    if not lines or not lines[0].strip() == BUNDLE_HEADER:
        _msg("bundle missing GENERATED header", "fail")
        all_ok = False
    else:
        _msg("bundle header present", "ok")

    if "window.FT = window.FT || {};" not in content:
        _msg("bundle missing FT initialization", "fail")
        all_ok = False
    else:
        _msg("FT initialization present", "ok")

    required_keys = {key for _, key in DATA_MAP}
    found_keys = set()

    # Parse one assignment per line.
    assignment_re = re.compile(r"window\.FT\.(DATA_\w+)\s*=\s*(\{.*\});\s*$")
    for line in lines:
        match = assignment_re.match(line)
        if not match:
            continue
        key = match.group(1)
        json_str = match.group(2)
        try:
            bundle_value = json.loads(json_str)
        except json.JSONDecodeError as e:
            _msg(f"{key} in bundle JSON parse error: {e}", "fail")
            all_ok = False
            continue
        found_keys.add(key)

        # Find source.
        filename = None
        for fn, k in DATA_MAP:
            if k == key:
                filename = fn
                break
        if filename is None:
            _msg(f"unexpected key in bundle: {key}", "fail")
            all_ok = False
            continue

        source_path = DATA_DIR / filename
        try:
            source_value = load_json(source_path)
        except json.JSONDecodeError as e:
            _msg(f"source {filename} parse error: {e}", "fail")
            all_ok = False
            continue

        if bundle_value == source_value:
            _msg(f"{key} semantic equal to {filename}", "ok")
        else:
            _msg(f"{key} differs from {filename}", "fail")
            all_ok = False

    missing = required_keys - found_keys
    if missing:
        for key in missing:
            _msg(f"bundle missing {key}", "fail")
        all_ok = False

    return 0 if all_ok else 1


# ---------------------------------------------------------------------------
# all
# ---------------------------------------------------------------------------

def all_cmd(args):
    print("all: validate -> sync -> doctor")
    code = validate(args)
    if code != 0:
        print("all stopped at validate")
        return code
    code = sync(args)
    if code != 0:
        print("all stopped at sync")
        return code
    code = doctor(args)
    if code != 0:
        print("all stopped at doctor")
        return code
    _msg("all completed", "ok")
    return 0


# ---------------------------------------------------------------------------
# merge-only
# ---------------------------------------------------------------------------

def merge_cmd(args):
    return merge(args)


# ---------------------------------------------------------------------------
# main
# ---------------------------------------------------------------------------

def main(argv=None):
    parser = argparse.ArgumentParser(description="EXPL-DATA-PIPELINE")
    sub = parser.add_subparsers(dest="command", required=True)

    sub.add_parser("validate", help="validate data/*.json")
    sub.add_parser("sync", help="merge explanations -> data/*.json -> js/data_bundle.js")
    sub.add_parser("doctor", help="check bundle and proof merge consistency")
    sub.add_parser("all", help="validate -> sync -> doctor")
    sub.add_parser("merge", help="merge explanations -> data/proof_scripts.json")

    args = parser.parse_args(argv)
    commands = {
        "validate": validate,
        "sync": sync,
        "doctor": doctor,
        "all": all_cmd,
        "merge": merge_cmd,
    }
    return commands[args.command](args)


if __name__ == "__main__":
    sys.exit(main())
